### ISSUE TITLE
firmware_arduino_ide.ino does not compile

### ISSUE THREAD

**Issue by YouMakeTech** [Nao974/choreograph-git#2]
Hello, thanks for sharing the code. Unfortunately I could not compile the firmware_arduino_ide.ino sketch. 
There are some inconsistencies in the name of the class. The filenames are choreograph.c and choreograph.h, but the class defined in these files is choregraph, without 'o'.
In firmware_arduino_ide.ino at line 5, you create an object chore of class choreograph, with the 'o', therefore the class is not defined.
In addition, #import <arduino.h> does not work on Linux because Linux is case sensitive. Should be replaced by #import <Arduino.h>.
Best Regards

**Comment by Nao974** [comment]
Thanks for your feedback.
Fixes assigned to hotfix-0.9 branch
