### ISSUE TITLE
Usage of undefined functions

### ISSUE THREAD

**Issue by nils-van-zuijlen** [Nao974/choreograph-git#5]
In method [`win_mboxe`](https://github.com/Nao974/choreograph-git/blob/f42dd078820c5d9394bb0d3122292cc1b01dfe09/choreograph/interface/frame_skeleton.py#L169), there are calls to two undefined functions, `mboxe_manager` and `serial_manager`. I searched across the whole repository, they are not present anywhere else.

**Comment by Nao974** [comment]
Problem identified. These functions come from a previous project that I have not yet integrated.
I clean the code and add more comments

**Comment by Nao974** [comment]
`frame_skeleton.py` is now cleaned up and with comments.
The errors on the call of these 2 functions are corrected.
